// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(string, tag="1")]
    pub channel_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub author_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub author_name: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub content: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Reaction {
    #[prost(message, optional, tag="1")]
    pub message: ::core::option::Option<Message>,
    #[prost(string, tag="2")]
    pub emoji: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
