// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CronJob {
    #[prost(string, tag="1")]
    pub cron: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub job: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
