// @generated
// This file is @generated by prost-build.
/// A cron job to run a task at a scheduled interval in the background.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CronJob {
    /// The cron schedule string to use for the cron job.
    ///
    /// Example (run every 5th minute):
    ///   */5 * * * *
    ///
    /// @see: <https://crontab.guru/>
    #[prost(string, tag="1")]
    pub cron: ::prost::alloc::string::String,
    /// A function name to call for each scheduled cron execution.
    #[prost(string, tag="2")]
    pub job: ::prost::alloc::string::String,
}
/// A one shot job to run a task at a scheduled interval in the background.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OneShotJob {
    /// The duration in seconds to wait until calling this job.
    #[prost(int32, tag="1")]
    pub duration: i32,
    /// A function name to call for each scheduled cron execution.
    #[prost(string, tag="2")]
    pub job: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
