// @generated
// This file is @generated by prost-build.
/// Database Query Results.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Results {
    /// An array of JSON strings.
    #[prost(string, repeated, tag="1")]
    pub rows: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// A prepared statement to execute on the database.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PreparedStatement {
    /// The SQL query to execute, using ? for placeholders.
    ///
    /// Example:
    ///   SELECT * FROM table WHERE id = ?
    #[prost(string, tag="1")]
    pub sql: ::prost::alloc::string::String,
    /// An array of values to substitute each ? placeholder in the SQL query with.
    #[prost(string, repeated, tag="2")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
