// @generated
// This file is @generated by prost-build.
/// A chat message.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    /// The channel id the message is from/to.
    #[prost(string, tag="1")]
    pub channel_id: ::prost::alloc::string::String,
    /// The id of the received message.
    #[prost(string, tag="2")]
    pub message_id: ::prost::alloc::string::String,
    /// The id of the author of the message.
    #[prost(string, tag="3")]
    pub author_id: ::prost::alloc::string::String,
    /// The name of the author of the message.
    #[prost(string, tag="4")]
    pub author_name: ::prost::alloc::string::String,
    /// The content of the message.
    #[prost(string, tag="5")]
    pub content: ::prost::alloc::string::String,
}
/// A reaction to a message.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Reaction {
    /// A message to react to.
    #[prost(message, optional, tag="1")]
    pub message: ::core::option::Option<Message>,
    /// A utf-8 emoji to react with.
    #[prost(string, tag="2")]
    pub emoji: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
