// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendMessageInput {
    #[prost(message, optional, tag="1")]
    pub message: ::core::option::Option<message::Message>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SendMessageOutput {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReactInput {
    #[prost(message, optional, tag="1")]
    pub reaction: ::core::option::Option<message::Reaction>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReactOutput {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbQueryInput {
    #[prost(message, optional, tag="1")]
    pub prepared_statement: ::core::option::Option<database::PreparedStatement>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbQueryOutput {
    #[prost(message, optional, tag="1")]
    pub results: ::core::option::Option<database::Results>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CronInput {
    #[prost(message, optional, tag="1")]
    pub cron_job: ::core::option::Option<cron::CronJob>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CronOutput {
}
// @@protoc_insertion_point(module)
